CREATE TABLE IF NOT EXISTS banners(
    id SERIAL PRIMARY KEY,
    content JSON,
    created_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOL NOT NULL DEFAULT true
);