version: '3.9'

services:
  server:
    build: .
    ports:
      - 8080:8080
    environment:
      - USER_TOKEN=user
      - ADMIN_TOKEN=admin
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banner_service
    volumes:
      - ./db/testdata:/testdata
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s
      timeout: 1s
      retries: 5