version: '3.9'

services:
  
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banner_service
    volumes:
      - ./db/testdata:/testdata
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 2s
    #   timeout: 1s
    #   retries: 5