env: dev

server:
  host: localhost
  port: 8080
  responseTime: 50ms
  rps: 1000
  bannerLifeCycle: 5m

database:
  dsn: postgres://postgres:postgres@localhost:5432/banner_service?sslmode=disable
  maxOpenConns: 10
  numberOfBannerVersions: 3